name: Bug report
description: Report a bug or issue
title: "[Bug]: "
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Describe the bug...
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: Step-by-step instructions
